name: Bastincloud
title: Bastincloud | kubernetes on raspberries
description: A blog where I write about my journey bootstrapping and maintaining a 
 kubernetes cluster on raspberries PI using talos.
tags:
  - blog
  - raspberry
  - kubernetes
  - bare-metal
  - on-premise
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: bastien.jeannelle@gmail.com
disqus_username: None
